# Generated by Django 5.1.1 on 2024-10-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modelname_poductcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='Poduct',
        ),
    ]
