# Generated by Django 5.1.1 on 2024-10-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_category_customer_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_items',
            new_name='order',
        ),
    ]
