# Generated by Django 5.1.1 on 2024-10-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='cutomer',
            new_name='customer',
        ),
    ]
